# Generated by Django 4.2.7 on 2024-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Process'), ('S', 'SUCCESS'), ('C', 'CANCELED')], max_length=1, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='url_for_payment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
